name: "QIIME2: build and test"
on: issue_comment

jobs:
  react:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/q2ci') }}
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            <br /> **Edit:** Running QIIME 2 CI...
          reactions: "+1"

  ci:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/q2ci') }}
    uses: qiime2/distributions/.github/workflows/lib-ci-dev.yaml@dev
    with:
      distro: moshpit
